name: training-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base
  - bioconductor-zlibbioc==1.48.0
  - bioconductor-dada2
  - r-phangorn
  - bioconductor-phyloseq
  - bioconductor-shortread
  - bioconductor-decipher
  - bioconductor-biostrings
  - r-ggplot2
